# This file was *autogenerated* from the file PrimeNumGenerator.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_35 = Integer(35); _sage_const_10 = Integer(10); _sage_const_20000 = Integer(20000)
import random as rand
"""
Generators a list of primes numbers in a range
Args:
    starting(int): the value to start from
    amount(int): the amount of values to search for
    pattern(int): the pattern for iterating over the values

Returns:
    num_list(tuple of (int,int))
    the first item is the number itself
    the second number is whether the number is prime or not
    1 for prime, 0 for even
"""
def gen_num_list(starting,amount,pattern):
    #creates a list
    num_list = list()
    for i in range(starting,starting+amount,pattern):
        #primes
        if( i in Primes()):
            num_list.append((i,_sage_const_1 ))
            #print i, "Prime!"
        #evens
        else:
            num_list.append((i,_sage_const_0 ))
            #print i, "Not Prime!"
    return num_list

"""
Generators a list of primes numbers randomly
Args:
    size(int): the maximum size of the number
    amount(int): the amount of values to search for
    split(bool): true for a 50-50 split, false otherwise
Returns:
    num_list(tuple of (int,int))
    the first item is the number itself
    the second number is whether the number is prime or not
    1 for prime, 0 for even
"""
def gen_rand_num_list(size,amount,split):
    #creates a list
    num_list = list()
    count = _sage_const_0 
    spot = _sage_const_0 
    while(count <= amount):
        number = rand.randint(_sage_const_1 ,size)
        #primes
        if(number in Primes()):
            if(spot == _sage_const_1  or split == False):
                num_list.append((number,_sage_const_1 ))
                count +=_sage_const_1 
                spot = _sage_const_0 
            #print i, "Prime!"
        #evens
        else:
            if(spot == _sage_const_0  or split == False):
                num_list.append((number,_sage_const_0 ))
                count +=_sage_const_1 
                spot = _sage_const_1 

            #print i, "Not Prime!"

    return num_list

"""
Creates a number with the amount specified
Args:
    amount(int): the amount of digits to use in the number
Returns:
    num(int): the integer being created
"""
def digit_count(amount):
    num = _sage_const_1 
    for i in range(amount-_sage_const_1 ):
        num *= _sage_const_10 
    return num

"""
Writes the numbers to a csv file
Args:
    num_list(a list of tuples): In the form (int,int)
        The first int is the number that was checked for primality
        The second int is 1 if prime, 0 otherwise.
    file_name(string): name of the file to output to
"""
def write_to_file(num_list,file_name):
    num_string = ""
    for elt in num_list:
        num_string += str(elt[_sage_const_0 ]) +"," + str(elt[_sage_const_1 ]) + '\n'
    #deletes the excess newline character
    num_string = num_string[:-_sage_const_1 ]

    file_write = open(file_name,"w")
    #headers
    file_write.write("Number,PoC\n")
    #writes all of the information to a file
    file_write.write(num_string)

x = gen_rand_num_list(digit_count(_sage_const_35 ),_sage_const_20000 ,False)

#num_list = gen_num_list(digit_count(30),10000,1)
write_to_file(x,"primes_notsplit.csv")
